/**
 * Generates lib/providerMarks.ts from the official SVGs in public/providers.
 *
 * The marks are copied without altering their geometry or their colors. Mono
 * marks declare no fill, so ProviderMark paints them with currentColor; color
 * marks keep their brand colors. Run after changing the provider list in
 * lib/site.ts.
 *
 *   bun run scripts/generate-marks.mjs
 */
import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const dir = join(root, "public", "providers");

const entries = readdirSync(dir)
  .filter((file) => file.endsWith(".svg"))
  .sort();

const marks = {};

for (const file of entries) {
  const raw = readFileSync(join(dir, file), "utf8");

  const viewBox = raw.match(/viewBox="([^"]+)"/)?.[1] ?? "0 0 24 24";
  const inner = raw
    .replace(/^[\s\S]*?<svg[^>]*>/, "")
    .replace(/<\/svg>\s*$/, "")
    .replace(/<title>[\s\S]*?<\/title>/g, "")
    .trim();

  marks[file.replace(/\.svg$/, "")] = { viewBox, inner };
}

const banner = `// Generated by scripts/generate-marks.mjs. Do not edit by hand.
// Official provider marks, unmodified in geometry and color.
`;

writeFileSync(
  join(root, "lib", "providerMarks.ts"),
  `${banner}
export type ProviderMark = { viewBox: string; inner: string };

export const providerMarks: Record<string, ProviderMark> = ${JSON.stringify(marks, null, 2)};
`,
  "utf8",
);

console.log(`Wrote ${Object.keys(marks).length} marks to lib/providerMarks.ts`);
